### PR TITLE
impl: avoid a warning about naming conventions

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by dtolnay** [comment]
Thanks! What is the code that is triggering this?

**Comment by mathstuf** [comment]
By the way, converting to uppercase makes a warning that it should be in camel case.

**Comment by dtolnay** [comment]
Strange, I haven't seen that before. I bet it's a consequence of https://github.com/rust-lang/rust/issues/43081 which is causing the compiler to randomly lose Span information and forget that these tokens came from a macro expansion (because many lints don't apply in macro generated code). In any case, the fix looks good to me.

**Comment by dtolnay** [comment]
Published in 0.1.2.

**Pull request merged**
